### ISSUE TITLE
Are workers in scope?

### ISSUE THREAD

**Issue by yoavweiss** [weizman/Same-Origin-Regulation-Policy#5]
They are mentioned as part of the terminology definition, but aren't mentioned elsewhere.

**Comment by weizman** [comment]
Great question,

Workers are part of the terminology definition because they are an important example to properly explaining what realms are.

However, in context of this proposal, Workers aren't relevant because the same origin concern refers to realms that have synchronous access to each other's graph, and by that can access/manipulate each other's internal intrinsics, DOM, global object, execution environment and more.

Easiest way to test this mentally is by telling whether `Array` of another realm is accessible to your realm or not:

```javascript
// in scope ("ƒ Array() { [native code] }")
document.body.appendChild(document.createElement('iframe')).contentWindow.Array;
open('about:blank').Array;
```

These techniques aren't relevant with Workers (no such access exists) and that's why they're out of scope here.

**Comment by yoavweiss** [comment]
Can't subworkers be used to e.g. grab overridden native prototypes from the global scope?

**Comment by weizman** [comment]
I'm not familiar with the term sub workers, but if you're referring to https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers then the answer is no

**Comment by eligrey** [comment]
I would like Web Workers to be in scope here. It helps support my use case for client-side network controls.

**Comment by eligrey** [comment]
> However, in context of this proposal, Workers aren't relevant because the same origin concern refers to realms that have synchronous access to each other's graph, and by that can access/manipulate each other's internal intrinsics, DOM, global object, execution environment and more.

Why limit RIC to the same-origin concern? It's perfectly suited in theory to other applications like network controls as well, and a RIC-like polyfill already exists that supports providing network controls onto worker and worklet realms.

**Comment by eligrey** [comment]
@weizman You [list "Application Monitoring" as a supported use case](https://github.com/WICG/Realms-Initialization-Control?tab=readme-ov-file#application-monitoring-security--errors--performance--ux) yet you claim in this thread that solving the same-origin concern is the only supported use case in-scope.

Please clarify your decision.

**Comment by weizman** [comment]
Solving the same origin concern by introducing this change to browsers will help support monitoring use cases. 

Leaving workers outside of scope does not make that statement less true.

I don't see the contradiction you suggest.

Please clarify.

And as for why it's left outside of scope, my reply in the thread above still stands, it's just a specific problem we're focusing on, and workers aren't part of it.

**Comment by eligrey** [comment]
Sorry, I misunderstood that you intended to exclude workers. I thought this was supposed to cover all realms from the name of the specification.
